version: '3.9'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/apiOpenAIDB
    depends_on:
      - db
    command: sh -c "sleep 5 && rm -rf .next && npm run build && npm run start"
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: apiOpenAIDB
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
volumes:
  postgres_data:
  

